export { ShortIntro } from './short-intro'
export { ServiceTeaser } from './service-teaser'
export { HomeLanding } from './home-landing'
export { Footer } from './footer/footer'
export { ContactSection } from './contact-section'
export { AboutTeaser, AboutDetailed } from './about'
export { Header } from './header'
export { SkillsSimple, SkillsDetailed } from './skills'
export { ProjectTile } from './project-tile'